import type { HousingListing } from "../../domain/entities.js";

const img = (seed: string, n: number): string[] =>
  Array.from({ length: n }, (_, i) => `https://picsum.photos/seed/${seed}-${i}/1200/900`);

/**
 * Fixed catalogue backing the demo. Deliberately includes duplicates, expired
 * listings, over-budget listings and records with missing optional fields so the
 * filtering and dedupe paths are exercised by real data rather than only by tests.
 */
export const MOCK_LISTINGS: HousingListing[] = [
  // ---------- Lund: the strong matches ----------
  {
    id: "mock-lund-001",
    provider: "mock",
    providerListingId: "LUND-001",
    canonicalUrl: "https://example.invalid/listings/LUND-001",
    title: "Furnished studio near Lund city campus",
    description:
      "Bright studio on a quiet street in Väster, ten minutes by bicycle from the main campus. Recently renovated with a small balcony facing the courtyard.",
    address: "Bredgatan 18, Lund",
    city: "Lund",
    area: "Väster",
    latitude: 55.7065,
    longitude: 13.1885,
    monthlyRent: 7450,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 27,
    furnished: true,
    availableFrom: "2026-08-18",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "balcony", "bicycle storage"],
    imageUrls: img("lund001", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-001@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-lund-002",
    provider: "mock",
    providerListingId: "LUND-002",
    canonicalUrl: "https://example.invalid/listings/LUND-002",
    title: "Student flat with balcony in Norra Fäladen",
    description:
      "One-room apartment in a well-kept student building. Shared laundry in the basement and a bus stop outside the door.",
    address: "Svenshögsvägen 4, Lund",
    city: "Lund",
    area: "Norra Fäladen",
    latitude: 55.7180,
    longitude: 13.1930,
    monthlyRent: 6900,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 31,
    furnished: true,
    availableFrom: "2026-08-15",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "balcony"],
    imageUrls: img("lund002", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-lund-003",
    provider: "mock",
    providerListingId: "LUND-003",
    canonicalUrl: "https://example.invalid/listings/LUND-003",
    title: "Two rooms close to LTH",
    description:
      "Spacious two-room apartment a short walk from the Faculty of Engineering. Unfurnished, with a proper kitchen and a desk nook.",
    address: "Tunavägen 39, Lund",
    city: "Lund",
    area: "Tuna",
    latitude: 55.7135,
    longitude: 13.2065,
    monthlyRent: 7900,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 48,
    furnished: false,
    availableFrom: "2026-08-20",
    availableTo: "2027-08-19",
    minimumRentalMonths: 12,
    amenities: ["laundry", "dishwasher", "bicycle storage"],
    imageUrls: img("lund003", 6),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-003@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-lund-004",
    provider: "mock",
    providerListingId: "LUND-004",
    canonicalUrl: "https://example.invalid/listings/LUND-004",
    title: "Room in shared corridor, Delphi",
    description: "Corridor room in a classic student housing area. Shared kitchen with eleven others.",
    address: "Delphivägen 2, Lund",
    city: "Lund",
    area: "Delphi",
    latitude: 55.7205,
    longitude: 13.2140,
    monthlyRent: 5200,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 18,
    furnished: true,
    availableFrom: "2026-08-25",
    availableTo: "2027-06-15",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("lund004", 3),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/LUND-004" },
    isActive: true,
  },
  // Duplicate of LUND-001 from a second feed, with a thinner record.
  {
    id: "mock-lund-001-dup",
    provider: "mock",
    providerListingId: "LUND-001-B",
    canonicalUrl: null,
    title: "Studio Bredgatan",
    description: null,
    address: "Bredgatan 18, Lund",
    city: "Lund",
    area: null,
    latitude: 55.7065,
    longitude: 13.1885,
    monthlyRent: 7450,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 27,
    furnished: true,
    availableFrom: "2026-08-18",
    availableTo: null,
    minimumRentalMonths: null,
    amenities: [],
    imageUrls: img("lund001b", 1),
    contactCapability: "manual_handoff",
    providerMetadata: {},
    isActive: true,
  },
  // Over budget for the demo profile.
  {
    id: "mock-lund-005",
    provider: "mock",
    providerListingId: "LUND-005",
    canonicalUrl: "https://example.invalid/listings/LUND-005",
    title: "Renovated three rooms in central Lund",
    description: "Large apartment on Stora Södergatan with a balcony over the street.",
    address: "Stora Södergatan 21, Lund",
    city: "Lund",
    area: "Centrum",
    latitude: 55.7020,
    longitude: 13.1930,
    monthlyRent: 14500,
    currency: "SEK",
    rooms: 3,
    sizeSquareMeters: 78,
    furnished: true,
    availableFrom: "2026-09-01",
    availableTo: "2027-08-31",
    minimumRentalMonths: 12,
    amenities: ["wifi", "dishwasher", "balcony", "elevator"],
    imageUrls: img("lund005", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-005@example.invalid" },
    isActive: true,
  },
  // Expired: available window already closed.
  {
    id: "mock-lund-006",
    provider: "mock",
    providerListingId: "LUND-006",
    canonicalUrl: "https://example.invalid/listings/LUND-006",
    title: "Sublet until spring (ended)",
    description: "Short sublet that has already finished.",
    address: "Kävlingevägen 8, Lund",
    city: "Lund",
    area: "Väster",
    latitude: 55.7090,
    longitude: 13.1820,
    monthlyRent: 6500,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 24,
    furnished: true,
    availableFrom: "2025-09-01",
    availableTo: "2026-05-31",
    minimumRentalMonths: 6,
    amenities: ["wifi"],
    imageUrls: img("lund006", 2),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-006@example.invalid" },
    isActive: true,
  },
  // Explicitly inactive.
  {
    id: "mock-lund-007",
    provider: "mock",
    providerListingId: "LUND-007",
    canonicalUrl: "https://example.invalid/listings/LUND-007",
    title: "Studio taken off the market",
    description: "Already rented out.",
    address: "Trollebergsvägen 3, Lund",
    city: "Lund",
    area: "Väster",
    latitude: 55.7040,
    longitude: 13.1780,
    monthlyRent: 7100,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 29,
    furnished: true,
    availableFrom: "2026-08-10",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("lund007", 2),
    contactCapability: "email",
    providerMetadata: {},
    isActive: false,
  },
  // Contact always fails — exercises the failure path.
  {
    id: "mock-lund-008",
    provider: "mock",
    providerListingId: "LUND-008",
    canonicalUrl: "https://example.invalid/listings/LUND-008",
    title: "Compact studio by the station",
    description: "Small but efficient studio two minutes from Lund C.",
    address: "Bangatan 12, Lund",
    city: "Lund",
    area: "Centrum",
    latitude: 55.7070,
    longitude: 13.1875,
    monthlyRent: 7800,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 25,
    furnished: true,
    availableFrom: "2026-08-22",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "elevator"],
    imageUrls: img("lund008", 4),
    contactCapability: "provider_api",
    providerMetadata: { simulateContactFailure: true },
    isActive: true,
  },
  // Missing several optional fields.
  {
    id: "mock-lund-009",
    provider: "mock",
    providerListingId: "LUND-009",
    canonicalUrl: null,
    title: "Room in house share, Klostergården",
    description: null,
    address: null,
    city: "Lund",
    area: "Klostergården",
    latitude: 55.6935,
    longitude: 13.1880,
    monthlyRent: 5900,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: null,
    furnished: null,
    availableFrom: "2026-08-19",
    availableTo: null,
    minimumRentalMonths: null,
    amenities: ["laundry"],
    imageUrls: img("lund009", 2),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/LUND-009" },
    isActive: true,
  },

  // ---------- Malmö ----------
  {
    id: "mock-malmo-001",
    provider: "mock",
    providerListingId: "MALMO-001",
    canonicalUrl: "https://example.invalid/listings/MALMO-001",
    title: "Modern studio in Västra Hamnen",
    description: "Newly built studio by the water, twelve minutes to Malmö University.",
    address: "Dockplatsen 12, Malmö",
    city: "Malmö",
    area: "Västra Hamnen",
    latitude: 55.6140,
    longitude: 12.9790,
    monthlyRent: 8900,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 33,
    furnished: true,
    availableFrom: "2026-08-15",
    availableTo: "2027-08-14",
    minimumRentalMonths: 12,
    amenities: ["wifi", "laundry", "elevator", "gym"],
    imageUrls: img("malmo001", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-m1@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-malmo-002",
    provider: "mock",
    providerListingId: "MALMO-002",
    canonicalUrl: "https://example.invalid/listings/MALMO-002",
    title: "Two rooms in Möllevången",
    description: "Lively neighbourhood, high ceilings, unfurnished.",
    address: "Kristianstadsgatan 9, Malmö",
    city: "Malmö",
    area: "Möllevången",
    latitude: 55.5920,
    longitude: 13.0100,
    monthlyRent: 8200,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 52,
    furnished: false,
    availableFrom: "2026-09-01",
    availableTo: "2027-08-31",
    minimumRentalMonths: 12,
    amenities: ["laundry", "bicycle storage"],
    imageUrls: img("malmo002", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-malmo-003",
    provider: "mock",
    providerListingId: "MALMO-003",
    canonicalUrl: "https://example.invalid/listings/MALMO-003",
    title: "Student room in Rosengård",
    description: "Affordable room with good bus connections to campus.",
    address: "Ramels väg 60, Malmö",
    city: "Malmö",
    area: "Rosengård",
    latitude: 55.5860,
    longitude: 13.0400,
    monthlyRent: 5400,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 21,
    furnished: true,
    availableFrom: "2026-08-12",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("malmo003", 3),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/MALMO-003" },
    isActive: true,
  },

  // ---------- Stockholm ----------
  {
    id: "mock-sthlm-001",
    provider: "mock",
    providerListingId: "STHLM-001",
    canonicalUrl: "https://example.invalid/listings/STHLM-001",
    title: "Studio in Kungsholmen",
    description: "Compact studio with a view over the canal, close to the metro.",
    address: "Sankt Eriksgatan 44, Stockholm",
    city: "Stockholm",
    area: "Kungsholmen",
    latitude: 59.3360,
    longitude: 18.0330,
    monthlyRent: 11200,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 28,
    furnished: true,
    availableFrom: "2026-08-20",
    availableTo: "2027-08-19",
    minimumRentalMonths: 12,
    amenities: ["wifi", "laundry", "elevator"],
    imageUrls: img("sthlm001", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-s1@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-sthlm-002",
    provider: "mock",
    providerListingId: "STHLM-002",
    canonicalUrl: "https://example.invalid/listings/STHLM-002",
    title: "Room in Lappkärrsberget",
    description: "Classic student area a short walk from Frescati.",
    address: "Lappkärrsberget 32, Stockholm",
    city: "Stockholm",
    area: "Lappkärrsberget",
    latitude: 59.3690,
    longitude: 18.0640,
    monthlyRent: 6100,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 19,
    furnished: true,
    availableFrom: "2026-08-16",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("sthlm002", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-sthlm-003",
    provider: "mock",
    providerListingId: "STHLM-003",
    canonicalUrl: "https://example.invalid/listings/STHLM-003",
    title: "Two rooms in Kista",
    description: "Close to KTH Kista and the tech cluster.",
    address: "Danmarksgatan 20, Kista",
    city: "Stockholm",
    area: "Kista",
    latitude: 59.4020,
    longitude: 17.9450,
    monthlyRent: 9800,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 55,
    furnished: false,
    availableFrom: "2026-08-25",
    availableTo: "2027-08-24",
    minimumRentalMonths: 12,
    amenities: ["laundry", "elevator", "dishwasher"],
    imageUrls: img("sthlm003", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-s3@example.invalid" },
    isActive: true,
  },

  // ---------- Uppsala ----------
  {
    id: "mock-uppsala-001",
    provider: "mock",
    providerListingId: "UPPS-001",
    canonicalUrl: "https://example.invalid/listings/UPPS-001",
    title: "Studio in Flogsta",
    description: "The classic Uppsala student experience, ten minutes by bicycle to campus.",
    address: "Flogstavägen 71, Uppsala",
    city: "Uppsala",
    area: "Flogsta",
    latitude: 59.8490,
    longitude: 17.5900,
    monthlyRent: 5800,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 24,
    furnished: true,
    availableFrom: "2026-08-14",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("upps001", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-uppsala-002",
    provider: "mock",
    providerListingId: "UPPS-002",
    canonicalUrl: "https://example.invalid/listings/UPPS-002",
    title: "Central one-room apartment",
    description: "Quiet flat near the cathedral, walking distance to English Park.",
    address: "Sysslomansgatan 14, Uppsala",
    city: "Uppsala",
    area: "Centrum",
    latitude: 59.8600,
    longitude: 17.6320,
    monthlyRent: 8400,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 36,
    furnished: true,
    availableFrom: "2026-08-20",
    availableTo: "2027-08-19",
    minimumRentalMonths: 12,
    amenities: ["wifi", "laundry", "balcony"],
    imageUrls: img("upps002", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-u2@example.invalid" },
    isActive: true,
  },

  // ---------- Gothenburg ----------
  {
    id: "mock-gbg-001",
    provider: "mock",
    providerListingId: "GBG-001",
    canonicalUrl: "https://example.invalid/listings/GBG-001",
    title: "Studio in Johanneberg",
    description: "Steps from Chalmers Johanneberg, furnished and ready to move into.",
    address: "Gibraltargatan 82, Göteborg",
    city: "Gothenburg",
    area: "Johanneberg",
    latitude: 57.6880,
    longitude: 11.9800,
    monthlyRent: 7600,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 26,
    furnished: true,
    availableFrom: "2026-08-17",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("gbg001", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-g1@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-gbg-002",
    provider: "mock",
    providerListingId: "GBG-002",
    canonicalUrl: "https://example.invalid/listings/GBG-002",
    title: "Two rooms in Majorna",
    description: "Characterful flat in a wooden landshövdingehus.",
    address: "Karl Johansgatan 45, Göteborg",
    city: "Gothenburg",
    area: "Majorna",
    latitude: 57.6990,
    longitude: 11.9280,
    monthlyRent: 8800,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 54,
    furnished: false,
    availableFrom: "2026-09-05",
    availableTo: "2027-09-04",
    minimumRentalMonths: 12,
    amenities: ["laundry"],
    imageUrls: img("gbg002", 3),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/GBG-002" },
    isActive: true,
  },
  {
    id: "mock-gbg-003",
    provider: "mock",
    providerListingId: "GBG-003",
    canonicalUrl: "https://example.invalid/listings/GBG-003",
    title: "Room near Lindholmen",
    description: "Small room in a shared flat, five minutes from Campus Lindholmen.",
    address: "Lindholmsallén 10, Göteborg",
    city: "Gothenburg",
    area: "Lindholmen",
    latitude: 57.7060,
    longitude: 11.9390,
    monthlyRent: 6200,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 20,
    furnished: true,
    availableFrom: "2026-08-21",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("gbg003", 3),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },

  // ---------- Lund: more of the strong matches ----------
  {
    id: "mock-lund-011",
    provider: "mock",
    providerListingId: "LUND-011",
    canonicalUrl: "https://example.invalid/listings/LUND-011",
    title: "Top-floor studio in Professorsstaden",
    description:
      "Attic studio with sloped ceilings and a skylight, on a leafy street a short walk from the university library.",
    address: "Tornavägen 6, Lund",
    city: "Lund",
    area: "Professorsstaden",
    latitude: 55.7118,
    longitude: 13.1968,
    monthlyRent: 7300,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 24,
    furnished: true,
    availableFrom: "2026-08-15",
    availableTo: "2027-07-15",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("lund011", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-011@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-lund-012",
    provider: "mock",
    providerListingId: "LUND-012",
    canonicalUrl: "https://example.invalid/listings/LUND-012",
    title: "One room with courtyard view, Östra Torn",
    description:
      "Ground-floor room facing a shared courtyard, close to the IKEA roundabout bus line into town.",
    address: "Ostra Torn 14, Lund",
    city: "Lund",
    area: "Östra Torn",
    latitude: 55.7168,
    longitude: 13.2196,
    monthlyRent: 6700,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 22,
    furnished: true,
    availableFrom: "2026-08-24",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("lund012", 3),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-lund-013",
    provider: "mock",
    providerListingId: "LUND-013",
    canonicalUrl: "https://example.invalid/listings/LUND-013",
    title: "Bright one-room flat in Järnåkra",
    description:
      "West-facing room that catches the afternoon light, ten minutes by bike along the canal path to LTH.",
    address: "Järnåkravägen 22, Lund",
    city: "Lund",
    area: "Järnåkra",
    latitude: 55.7082,
    longitude: 13.1748,
    monthlyRent: 6950,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 29,
    furnished: false,
    availableFrom: "2026-08-17",
    availableTo: "2027-07-31",
    minimumRentalMonths: 8,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("lund013", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-013@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-lund-014",
    provider: "mock",
    providerListingId: "LUND-014",
    canonicalUrl: "https://example.invalid/listings/LUND-014",
    title: "Renovated studio in Kobjer",
    description: "Small new-build studio near the Kobjer sports fields, quiet at night.",
    address: "Kobjersvägen 9, Lund",
    city: "Lund",
    area: "Kobjer",
    latitude: 55.7224,
    longitude: 13.1786,
    monthlyRent: 7150,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 26,
    furnished: true,
    availableFrom: "2026-08-28",
    availableTo: "2027-08-27",
    minimumRentalMonths: 12,
    amenities: ["wifi", "laundry", "elevator"],
    imageUrls: img("lund014", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-lund-015",
    provider: "mock",
    providerListingId: "LUND-015",
    canonicalUrl: "https://example.invalid/listings/LUND-015",
    title: "Two rooms in Gunnesbo",
    description:
      "Simple two-room flat near the ESS site, on the bus line that runs straight to the north campus.",
    address: "Gunnesbovägen 31, Lund",
    city: "Lund",
    area: "Gunnesbo",
    latitude: 55.7276,
    longitude: 13.1694,
    monthlyRent: 8600,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 46,
    furnished: false,
    availableFrom: "2026-09-01",
    availableTo: "2027-08-31",
    minimumRentalMonths: 12,
    amenities: ["laundry", "bicycle storage"],
    imageUrls: img("lund015", 3),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/LUND-015" },
    isActive: true,
  },
  {
    id: "mock-lund-016",
    provider: "mock",
    providerListingId: "LUND-016",
    canonicalUrl: "https://example.invalid/listings/LUND-016",
    title: "Corridor room in Klostergården",
    description: "Shared corridor with seven neighbours, five minutes' walk to the bus into town.",
    address: "Klostergårdsvägen 40, Lund",
    city: "Lund",
    area: "Klostergården",
    latitude: 55.6928,
    longitude: 13.1902,
    monthlyRent: 5450,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 17,
    furnished: true,
    availableFrom: "2026-08-13",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("lund016", 2),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/LUND-016" },
    isActive: true,
  },
  {
    id: "mock-lund-017",
    provider: "mock",
    providerListingId: "LUND-017",
    canonicalUrl: "https://example.invalid/listings/LUND-017",
    title: "Studio with balcony in Väster",
    description: "Second-floor studio with a small south-facing balcony, close to Stadsparken.",
    address: "Dammhagvägen 5, Lund",
    city: "Lund",
    area: "Väster",
    latitude: 55.7048,
    longitude: 13.1832,
    monthlyRent: 7550,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 28,
    furnished: true,
    availableFrom: "2026-08-19",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "balcony"],
    imageUrls: img("lund017", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-017@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-lund-018",
    provider: "mock",
    providerListingId: "LUND-018",
    canonicalUrl: "https://example.invalid/listings/LUND-018",
    title: "Compact room near Tuna",
    description: "Simply furnished room a few streets from the Faculty of Engineering.",
    address: "Tunavägen 61, Lund",
    city: "Lund",
    area: "Tuna",
    latitude: 55.7151,
    longitude: 13.2088,
    monthlyRent: 6300,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 19,
    furnished: true,
    availableFrom: "2026-08-23",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("lund018", 3),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-lund-019",
    provider: "mock",
    providerListingId: "LUND-019",
    canonicalUrl: "https://example.invalid/listings/LUND-019",
    title: "One-and-a-half rooms in Delphi",
    description: "Slightly larger than the standard corridor room, with its own small kitchenette.",
    address: "Delphivägen 18, Lund",
    city: "Lund",
    area: "Delphi",
    latitude: 55.7213,
    longitude: 13.2117,
    monthlyRent: 6850,
    currency: "SEK",
    rooms: 1.5,
    sizeSquareMeters: 32,
    furnished: true,
    availableFrom: "2026-08-16",
    availableTo: "2027-08-15",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("lund019", 3),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-019@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-lund-020",
    provider: "mock",
    providerListingId: "LUND-020",
    canonicalUrl: "https://example.invalid/listings/LUND-020",
    title: "Central studio on Bantorget",
    description: "Fifth-floor studio overlooking the square, lift in the building.",
    address: "Bantorget 3, Lund",
    city: "Lund",
    area: "Centrum",
    latitude: 55.7062,
    longitude: 13.1902,
    monthlyRent: 8900,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 34,
    furnished: true,
    availableFrom: "2026-09-01",
    availableTo: "2027-08-31",
    minimumRentalMonths: 12,
    amenities: ["wifi", "elevator", "dishwasher"],
    imageUrls: img("lund020", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-020@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-lund-021",
    provider: "mock",
    providerListingId: "LUND-021",
    canonicalUrl: "https://example.invalid/listings/LUND-021",
    title: "Two rooms in Norra Fäladen",
    description: "Family-sized layout let as a student flat, with a proper study nook by the window.",
    address: "Sparvvägen 11, Lund",
    city: "Lund",
    area: "Norra Fäladen",
    latitude: 55.7192,
    longitude: 13.1958,
    monthlyRent: 8100,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 44,
    furnished: false,
    availableFrom: "2026-08-27",
    availableTo: "2027-08-26",
    minimumRentalMonths: 10,
    amenities: ["laundry", "dishwasher", "bicycle storage"],
    imageUrls: img("lund021", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-lund-022",
    provider: "mock",
    providerListingId: "LUND-022",
    canonicalUrl: "https://example.invalid/listings/LUND-022",
    title: "Ground-floor studio in Järnåkra",
    description: "Own entrance from the garden side, popular with cyclists heading to LTH.",
    address: "Järnåkravägen 8, Lund",
    city: "Lund",
    area: "Järnåkra",
    latitude: 55.7076,
    longitude: 13.1761,
    monthlyRent: 6600,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 23,
    furnished: true,
    availableFrom: "2026-08-30",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("lund022", 3),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/LUND-022" },
    isActive: true,
  },
  // Missing several optional fields, like LUND-009 above.
  {
    id: "mock-lund-023",
    provider: "mock",
    providerListingId: "LUND-023",
    canonicalUrl: null,
    title: "Room in shared house, Gunnesbo",
    description: null,
    address: null,
    city: "Lund",
    area: null,
    latitude: 55.7268,
    longitude: 13.1712,
    monthlyRent: 5700,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: null,
    furnished: null,
    availableFrom: "2026-08-22",
    availableTo: null,
    minimumRentalMonths: null,
    amenities: ["wifi"],
    imageUrls: img("lund023", 2),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/LUND-023" },
    isActive: true,
  },
  // Near-duplicate of LUND-011 from a second feed, thinner record.
  {
    id: "mock-lund-024",
    provider: "mock",
    providerListingId: "LUND-011-B",
    canonicalUrl: null,
    title: "Studio Tornavägen",
    description: "Attic studio near the library, listed via a partner site.",
    address: "Tornavägen 6, Lund",
    city: "Lund",
    area: "Professorsstaden",
    latitude: 55.7118,
    longitude: 13.1968,
    monthlyRent: 7300,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 24,
    furnished: true,
    availableFrom: "2026-08-15",
    availableTo: "2027-07-15",
    minimumRentalMonths: 6,
    amenities: ["wifi"],
    imageUrls: img("lund024", 1),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },

  // ---------- Malmö: more listings ----------
  {
    id: "mock-malmo-004",
    provider: "mock",
    providerListingId: "MALMO-004",
    canonicalUrl: "https://example.invalid/listings/MALMO-004",
    title: "Studio near Triangeln",
    description: "Bright studio one stop from Malmö C, close to the Triangeln shopping street.",
    address: "Fersens väg 15, Malmö",
    city: "Malmö",
    area: "Centrum",
    latitude: 55.5934,
    longitude: 13.0006,
    monthlyRent: 8600,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 30,
    furnished: true,
    availableFrom: "2026-08-18",
    availableTo: "2027-08-17",
    minimumRentalMonths: 12,
    amenities: ["wifi", "laundry", "elevator"],
    imageUrls: img("malmo004", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-m4@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-malmo-005",
    provider: "mock",
    providerListingId: "MALMO-005",
    canonicalUrl: "https://example.invalid/listings/MALMO-005",
    title: "One room in Sofielund",
    description: "Modest room in an up-and-coming neighbourhood, direct bus to the university.",
    address: "Ystadvägen 22, Malmö",
    city: "Malmö",
    area: "Sofielund",
    latitude: 55.5885,
    longitude: 13.0175,
    monthlyRent: 6100,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 24,
    furnished: true,
    availableFrom: "2026-08-24",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("malmo005", 3),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-malmo-006",
    provider: "mock",
    providerListingId: "MALMO-006",
    canonicalUrl: "https://example.invalid/listings/MALMO-006",
    title: "Two rooms in Limhamn",
    description: "Quiet coastal neighbourhood, unfurnished, with a shared bike shed.",
    address: "Linnégatan 8, Malmö",
    city: "Malmö",
    area: "Limhamn",
    latitude: 55.5735,
    longitude: 12.9330,
    monthlyRent: 8950,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 50,
    furnished: false,
    availableFrom: "2026-09-03",
    availableTo: "2027-09-02",
    minimumRentalMonths: 12,
    amenities: ["laundry", "bicycle storage"],
    imageUrls: img("malmo006", 3),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/MALMO-006" },
    isActive: true,
  },
  // Inactive and over budget: already let, and priced above the demo profile.
  {
    id: "mock-malmo-007",
    provider: "mock",
    providerListingId: "MALMO-007",
    canonicalUrl: "https://example.invalid/listings/MALMO-007",
    title: "Renovated three rooms in Västra Hamnen (let)",
    description: "Waterfront apartment with a sea view, already taken off the market.",
    address: "Universitetsholmens allé 6, Malmö",
    city: "Malmö",
    area: "Västra Hamnen",
    latitude: 55.6172,
    longitude: 12.9765,
    monthlyRent: 16200,
    currency: "SEK",
    rooms: 3,
    sizeSquareMeters: 82,
    furnished: true,
    availableFrom: "2026-08-15",
    availableTo: "2027-08-14",
    minimumRentalMonths: 12,
    amenities: ["wifi", "dishwasher", "elevator", "gym"],
    imageUrls: img("malmo007", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-m7@example.invalid" },
    isActive: false,
  },

  // ---------- Stockholm: more listings ----------
  {
    id: "mock-sthlm-004",
    provider: "mock",
    providerListingId: "STHLM-004",
    canonicalUrl: "https://example.invalid/listings/STHLM-004",
    title: "Room in Danderyd student housing",
    description: "Compact room in a student block near KI Solna, bike path along the whole route.",
    address: "Studentvägen 9, Stockholm",
    city: "Stockholm",
    area: "Solna",
    latitude: 59.3540,
    longitude: 18.0230,
    monthlyRent: 6400,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 18,
    furnished: true,
    availableFrom: "2026-08-19",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("sthlm004", 3),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-sthlm-005",
    provider: "mock",
    providerListingId: "STHLM-005",
    canonicalUrl: "https://example.invalid/listings/STHLM-005",
    title: "Studio in Hagalund",
    description: "Small studio close to the Karolinska campus, five minutes from the metro.",
    address: "Hagalundsgatan 14, Solna",
    city: "Stockholm",
    area: "Hagalund",
    latitude: 59.3608,
    longitude: 18.0122,
    monthlyRent: 8700,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 27,
    furnished: true,
    availableFrom: "2026-08-21",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "elevator"],
    imageUrls: img("sthlm005", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-s5@example.invalid" },
    isActive: true,
  },
  // Inactive and over budget: a management-company listing pulled after letting.
  {
    id: "mock-sthlm-006",
    provider: "mock",
    providerListingId: "STHLM-006",
    canonicalUrl: "https://example.invalid/listings/STHLM-006",
    title: "Two rooms in Östermalm (let)",
    description: "Premium address near the embassies, already reserved by another tenant.",
    address: "Karlavägen 60, Stockholm",
    city: "Stockholm",
    area: "Östermalm",
    latitude: 59.3400,
    longitude: 18.0850,
    monthlyRent: 18500,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 58,
    furnished: true,
    availableFrom: "2026-08-20",
    availableTo: "2027-08-19",
    minimumRentalMonths: 12,
    amenities: ["wifi", "elevator", "dishwasher"],
    imageUrls: img("sthlm006", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-s6@example.invalid" },
    isActive: false,
  },

  // ---------- Uppsala: more listings ----------
  {
    id: "mock-uppsala-003",
    provider: "mock",
    providerListingId: "UPPS-003",
    canonicalUrl: "https://example.invalid/listings/UPPS-003",
    title: "Room in Kantorsgatan corridor",
    description: "Classic Uppsala corridor room, shared kitchen, bike ride to the English Park.",
    address: "Kantorsgatan 5, Uppsala",
    city: "Uppsala",
    area: "Eriksberg",
    latitude: 59.8465,
    longitude: 17.6215,
    monthlyRent: 5600,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 18,
    furnished: true,
    availableFrom: "2026-08-17",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("upps003", 3),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-uppsala-004",
    provider: "mock",
    providerListingId: "UPPS-004",
    canonicalUrl: "https://example.invalid/listings/UPPS-004",
    title: "Studio near Uppsala Science Park",
    description: "Modern studio a short walk from the Biomedical Centre, furnished throughout.",
    address: "Dag Hammarskjölds väg 34, Uppsala",
    city: "Uppsala",
    area: "Kåbo",
    latitude: 59.8390,
    longitude: 17.6470,
    monthlyRent: 8300,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 30,
    furnished: true,
    availableFrom: "2026-08-24",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("upps004", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-u4@example.invalid" },
    isActive: true,
  },
  // Inactive and over budget: taken off the market before term start.
  {
    id: "mock-uppsala-005",
    provider: "mock",
    providerListingId: "UPPS-005",
    canonicalUrl: "https://example.invalid/listings/UPPS-005",
    title: "Three rooms near the castle (let)",
    description: "Elegant apartment overlooking the castle park, no longer on the market.",
    address: "Slottsgränd 4, Uppsala",
    city: "Uppsala",
    area: "Centrum",
    latitude: 59.8555,
    longitude: 17.6335,
    monthlyRent: 15800,
    currency: "SEK",
    rooms: 3,
    sizeSquareMeters: 76,
    furnished: true,
    availableFrom: "2026-08-18",
    availableTo: "2027-08-17",
    minimumRentalMonths: 12,
    amenities: ["wifi", "dishwasher", "elevator"],
    imageUrls: img("upps005", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-u5@example.invalid" },
    isActive: false,
  },

  // ---------- Gothenburg: more listings ----------
  {
    id: "mock-gbg-004",
    provider: "mock",
    providerListingId: "GBG-004",
    canonicalUrl: "https://example.invalid/listings/GBG-004",
    title: "Studio in Guldheden",
    description: "Hillside studio with a view over the botanical garden, ten minutes to Chalmers by foot.",
    address: "Doktor Fries Torg 6, Göteborg",
    city: "Gothenburg",
    area: "Guldheden",
    latitude: 57.6825,
    longitude: 11.9575,
    monthlyRent: 7900,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 29,
    furnished: true,
    availableFrom: "2026-08-16",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("gbg004", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-gbg-005",
    provider: "mock",
    providerListingId: "GBG-005",
    canonicalUrl: "https://example.invalid/listings/GBG-005",
    title: "Room in Olskroken",
    description: "Simple room close to the tram, fifteen minutes to Campus Johanneberg.",
    address: "Olskroksgatan 33, Göteborg",
    city: "Gothenburg",
    area: "Olskroken",
    latitude: 57.7075,
    longitude: 12.0035,
    monthlyRent: 5900,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 20,
    furnished: true,
    availableFrom: "2026-08-25",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("gbg005", 3),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/GBG-005" },
    isActive: true,
  },
  // Inactive and over budget: corporate let pulled from the market.
  {
    id: "mock-gbg-006",
    provider: "mock",
    providerListingId: "GBG-006",
    canonicalUrl: "https://example.invalid/listings/GBG-006",
    title: "Two rooms in Vasastan (let)",
    description: "Period apartment near Avenyn, already assigned to a corporate tenant.",
    address: "Vasagatan 41, Göteborg",
    city: "Gothenburg",
    area: "Vasastan",
    latitude: 57.6975,
    longitude: 11.9720,
    monthlyRent: 14300,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 60,
    furnished: true,
    availableFrom: "2026-08-15",
    availableTo: "2027-08-14",
    minimumRentalMonths: 12,
    amenities: ["wifi", "elevator", "dishwasher"],
    imageUrls: img("gbg006", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-g6@example.invalid" },
    isActive: false,
  },
];
