import type { HousingListing } from "../../domain/entities.js";

const img = (seed: string, n: number): string[] =>
  Array.from({ length: n }, (_, i) => `https://picsum.photos/seed/${seed}-${i}/1200/900`);

/**
 * Fixed catalogue backing the demo. Deliberately includes duplicates, expired
 * listings, over-budget listings and records with missing optional fields so the
 * filtering and dedupe paths are exercised by real data rather than only by tests.
 */
export const MOCK_LISTINGS: HousingListing[] = [
  // ---------- Lund: the strong matches ----------
  {
    id: "mock-lund-001",
    provider: "mock",
    providerListingId: "LUND-001",
    canonicalUrl: "https://example.invalid/listings/LUND-001",
    title: "Furnished studio near Lund city campus",
    description:
      "Bright studio on a quiet street in Väster, ten minutes by bicycle from the main campus. Recently renovated with a small balcony facing the courtyard.",
    address: "Bredgatan 18, Lund",
    city: "Lund",
    area: "Väster",
    latitude: 55.7065,
    longitude: 13.1885,
    monthlyRent: 7450,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 27,
    furnished: true,
    availableFrom: "2026-08-18",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "balcony", "bicycle storage"],
    imageUrls: img("lund001", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-001@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-lund-002",
    provider: "mock",
    providerListingId: "LUND-002",
    canonicalUrl: "https://example.invalid/listings/LUND-002",
    title: "Student flat with balcony in Norra Fäladen",
    description:
      "One-room apartment in a well-kept student building. Shared laundry in the basement and a bus stop outside the door.",
    address: "Svenshögsvägen 4, Lund",
    city: "Lund",
    area: "Norra Fäladen",
    latitude: 55.7180,
    longitude: 13.1930,
    monthlyRent: 6900,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 31,
    furnished: true,
    availableFrom: "2026-08-15",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "balcony"],
    imageUrls: img("lund002", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-lund-003",
    provider: "mock",
    providerListingId: "LUND-003",
    canonicalUrl: "https://example.invalid/listings/LUND-003",
    title: "Two rooms close to LTH",
    description:
      "Spacious two-room apartment a short walk from the Faculty of Engineering. Unfurnished, with a proper kitchen and a desk nook.",
    address: "Tunavägen 39, Lund",
    city: "Lund",
    area: "Tuna",
    latitude: 55.7135,
    longitude: 13.2065,
    monthlyRent: 7900,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 48,
    furnished: false,
    availableFrom: "2026-08-20",
    availableTo: "2027-08-19",
    minimumRentalMonths: 12,
    amenities: ["laundry", "dishwasher", "bicycle storage"],
    imageUrls: img("lund003", 6),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-003@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-lund-004",
    provider: "mock",
    providerListingId: "LUND-004",
    canonicalUrl: "https://example.invalid/listings/LUND-004",
    title: "Room in shared corridor, Delphi",
    description: "Corridor room in a classic student housing area. Shared kitchen with eleven others.",
    address: "Delphivägen 2, Lund",
    city: "Lund",
    area: "Delphi",
    latitude: 55.7205,
    longitude: 13.2140,
    monthlyRent: 5200,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 18,
    furnished: true,
    availableFrom: "2026-08-25",
    availableTo: "2027-06-15",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("lund004", 3),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/LUND-004" },
    isActive: true,
  },
  // Duplicate of LUND-001 from a second feed, with a thinner record.
  {
    id: "mock-lund-001-dup",
    provider: "mock",
    providerListingId: "LUND-001-B",
    canonicalUrl: null,
    title: "Studio Bredgatan",
    description: null,
    address: "Bredgatan 18, Lund",
    city: "Lund",
    area: null,
    latitude: 55.7065,
    longitude: 13.1885,
    monthlyRent: 7450,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 27,
    furnished: true,
    availableFrom: "2026-08-18",
    availableTo: null,
    minimumRentalMonths: null,
    amenities: [],
    imageUrls: img("lund001b", 1),
    contactCapability: "manual_handoff",
    providerMetadata: {},
    isActive: true,
  },
  // Over budget for the demo profile.
  {
    id: "mock-lund-005",
    provider: "mock",
    providerListingId: "LUND-005",
    canonicalUrl: "https://example.invalid/listings/LUND-005",
    title: "Renovated three rooms in central Lund",
    description: "Large apartment on Stora Södergatan with a balcony over the street.",
    address: "Stora Södergatan 21, Lund",
    city: "Lund",
    area: "Centrum",
    latitude: 55.7020,
    longitude: 13.1930,
    monthlyRent: 14500,
    currency: "SEK",
    rooms: 3,
    sizeSquareMeters: 78,
    furnished: true,
    availableFrom: "2026-09-01",
    availableTo: "2027-08-31",
    minimumRentalMonths: 12,
    amenities: ["wifi", "dishwasher", "balcony", "elevator"],
    imageUrls: img("lund005", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-005@example.invalid" },
    isActive: true,
  },
  // Expired: available window already closed.
  {
    id: "mock-lund-006",
    provider: "mock",
    providerListingId: "LUND-006",
    canonicalUrl: "https://example.invalid/listings/LUND-006",
    title: "Sublet until spring (ended)",
    description: "Short sublet that has already finished.",
    address: "Kävlingevägen 8, Lund",
    city: "Lund",
    area: "Väster",
    latitude: 55.7090,
    longitude: 13.1820,
    monthlyRent: 6500,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 24,
    furnished: true,
    availableFrom: "2025-09-01",
    availableTo: "2026-05-31",
    minimumRentalMonths: 6,
    amenities: ["wifi"],
    imageUrls: img("lund006", 2),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-006@example.invalid" },
    isActive: true,
  },
  // Explicitly inactive.
  {
    id: "mock-lund-007",
    provider: "mock",
    providerListingId: "LUND-007",
    canonicalUrl: "https://example.invalid/listings/LUND-007",
    title: "Studio taken off the market",
    description: "Already rented out.",
    address: "Trollebergsvägen 3, Lund",
    city: "Lund",
    area: "Väster",
    latitude: 55.7040,
    longitude: 13.1780,
    monthlyRent: 7100,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 29,
    furnished: true,
    availableFrom: "2026-08-10",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("lund007", 2),
    contactCapability: "email",
    providerMetadata: {},
    isActive: false,
  },
  // Contact always fails — exercises the failure path.
  {
    id: "mock-lund-008",
    provider: "mock",
    providerListingId: "LUND-008",
    canonicalUrl: "https://example.invalid/listings/LUND-008",
    title: "Compact studio by the station",
    description: "Small but efficient studio two minutes from Lund C.",
    address: "Bangatan 12, Lund",
    city: "Lund",
    area: "Centrum",
    latitude: 55.7070,
    longitude: 13.1875,
    monthlyRent: 7800,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 25,
    furnished: true,
    availableFrom: "2026-08-22",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "elevator"],
    imageUrls: img("lund008", 4),
    contactCapability: "provider_api",
    providerMetadata: { simulateContactFailure: true },
    isActive: true,
  },
  // Missing several optional fields.
  {
    id: "mock-lund-009",
    provider: "mock",
    providerListingId: "LUND-009",
    canonicalUrl: null,
    title: "Room in house share, Klostergården",
    description: null,
    address: null,
    city: "Lund",
    area: "Klostergården",
    latitude: 55.6935,
    longitude: 13.1880,
    monthlyRent: 5900,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: null,
    furnished: null,
    availableFrom: "2026-08-19",
    availableTo: null,
    minimumRentalMonths: null,
    amenities: ["laundry"],
    imageUrls: img("lund009", 2),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/LUND-009" },
    isActive: true,
  },

  // ---------- Malmö ----------
  {
    id: "mock-malmo-001",
    provider: "mock",
    providerListingId: "MALMO-001",
    canonicalUrl: "https://example.invalid/listings/MALMO-001",
    title: "Modern studio in Västra Hamnen",
    description: "Newly built studio by the water, twelve minutes to Malmö University.",
    address: "Dockplatsen 12, Malmö",
    city: "Malmö",
    area: "Västra Hamnen",
    latitude: 55.6140,
    longitude: 12.9790,
    monthlyRent: 8900,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 33,
    furnished: true,
    availableFrom: "2026-08-15",
    availableTo: "2027-08-14",
    minimumRentalMonths: 12,
    amenities: ["wifi", "laundry", "elevator", "gym"],
    imageUrls: img("malmo001", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-m1@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-malmo-002",
    provider: "mock",
    providerListingId: "MALMO-002",
    canonicalUrl: "https://example.invalid/listings/MALMO-002",
    title: "Two rooms in Möllevången",
    description: "Lively neighbourhood, high ceilings, unfurnished.",
    address: "Kristianstadsgatan 9, Malmö",
    city: "Malmö",
    area: "Möllevången",
    latitude: 55.5920,
    longitude: 13.0100,
    monthlyRent: 8200,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 52,
    furnished: false,
    availableFrom: "2026-09-01",
    availableTo: "2027-08-31",
    minimumRentalMonths: 12,
    amenities: ["laundry", "bicycle storage"],
    imageUrls: img("malmo002", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-malmo-003",
    provider: "mock",
    providerListingId: "MALMO-003",
    canonicalUrl: "https://example.invalid/listings/MALMO-003",
    title: "Student room in Rosengård",
    description: "Affordable room with good bus connections to campus.",
    address: "Ramels väg 60, Malmö",
    city: "Malmö",
    area: "Rosengård",
    latitude: 55.5860,
    longitude: 13.0400,
    monthlyRent: 5400,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 21,
    furnished: true,
    availableFrom: "2026-08-12",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("malmo003", 3),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/MALMO-003" },
    isActive: true,
  },

  // ---------- Stockholm ----------
  {
    id: "mock-sthlm-001",
    provider: "mock",
    providerListingId: "STHLM-001",
    canonicalUrl: "https://example.invalid/listings/STHLM-001",
    title: "Studio in Kungsholmen",
    description: "Compact studio with a view over the canal, close to the metro.",
    address: "Sankt Eriksgatan 44, Stockholm",
    city: "Stockholm",
    area: "Kungsholmen",
    latitude: 59.3360,
    longitude: 18.0330,
    monthlyRent: 11200,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 28,
    furnished: true,
    availableFrom: "2026-08-20",
    availableTo: "2027-08-19",
    minimumRentalMonths: 12,
    amenities: ["wifi", "laundry", "elevator"],
    imageUrls: img("sthlm001", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-s1@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-sthlm-002",
    provider: "mock",
    providerListingId: "STHLM-002",
    canonicalUrl: "https://example.invalid/listings/STHLM-002",
    title: "Room in Lappkärrsberget",
    description: "Classic student area a short walk from Frescati.",
    address: "Lappkärrsberget 32, Stockholm",
    city: "Stockholm",
    area: "Lappkärrsberget",
    latitude: 59.3690,
    longitude: 18.0640,
    monthlyRent: 6100,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 19,
    furnished: true,
    availableFrom: "2026-08-16",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("sthlm002", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-sthlm-003",
    provider: "mock",
    providerListingId: "STHLM-003",
    canonicalUrl: "https://example.invalid/listings/STHLM-003",
    title: "Two rooms in Kista",
    description: "Close to KTH Kista and the tech cluster.",
    address: "Danmarksgatan 20, Kista",
    city: "Stockholm",
    area: "Kista",
    latitude: 59.4020,
    longitude: 17.9450,
    monthlyRent: 9800,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 55,
    furnished: false,
    availableFrom: "2026-08-25",
    availableTo: "2027-08-24",
    minimumRentalMonths: 12,
    amenities: ["laundry", "elevator", "dishwasher"],
    imageUrls: img("sthlm003", 4),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-s3@example.invalid" },
    isActive: true,
  },

  // ---------- Uppsala ----------
  {
    id: "mock-uppsala-001",
    provider: "mock",
    providerListingId: "UPPS-001",
    canonicalUrl: "https://example.invalid/listings/UPPS-001",
    title: "Studio in Flogsta",
    description: "The classic Uppsala student experience, ten minutes by bicycle to campus.",
    address: "Flogstavägen 71, Uppsala",
    city: "Uppsala",
    area: "Flogsta",
    latitude: 59.8490,
    longitude: 17.5900,
    monthlyRent: 5800,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 24,
    furnished: true,
    availableFrom: "2026-08-14",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("upps001", 4),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
  {
    id: "mock-uppsala-002",
    provider: "mock",
    providerListingId: "UPPS-002",
    canonicalUrl: "https://example.invalid/listings/UPPS-002",
    title: "Central one-room apartment",
    description: "Quiet flat near the cathedral, walking distance to English Park.",
    address: "Sysslomansgatan 14, Uppsala",
    city: "Uppsala",
    area: "Centrum",
    latitude: 59.8600,
    longitude: 17.6320,
    monthlyRent: 8400,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 36,
    furnished: true,
    availableFrom: "2026-08-20",
    availableTo: "2027-08-19",
    minimumRentalMonths: 12,
    amenities: ["wifi", "laundry", "balcony"],
    imageUrls: img("upps002", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-u2@example.invalid" },
    isActive: true,
  },

  // ---------- Gothenburg ----------
  {
    id: "mock-gbg-001",
    provider: "mock",
    providerListingId: "GBG-001",
    canonicalUrl: "https://example.invalid/listings/GBG-001",
    title: "Studio in Johanneberg",
    description: "Steps from Chalmers Johanneberg, furnished and ready to move into.",
    address: "Gibraltargatan 82, Göteborg",
    city: "Gothenburg",
    area: "Johanneberg",
    latitude: 57.6880,
    longitude: 11.9800,
    monthlyRent: 7600,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 26,
    furnished: true,
    availableFrom: "2026-08-17",
    availableTo: "2027-07-31",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry", "bicycle storage"],
    imageUrls: img("gbg001", 5),
    contactCapability: "email",
    providerMetadata: { landlordEmail: "landlord-g1@example.invalid" },
    isActive: true,
  },
  {
    id: "mock-gbg-002",
    provider: "mock",
    providerListingId: "GBG-002",
    canonicalUrl: "https://example.invalid/listings/GBG-002",
    title: "Two rooms in Majorna",
    description: "Characterful flat in a wooden landshövdingehus.",
    address: "Karl Johansgatan 45, Göteborg",
    city: "Gothenburg",
    area: "Majorna",
    latitude: 57.6990,
    longitude: 11.9280,
    monthlyRent: 8800,
    currency: "SEK",
    rooms: 2,
    sizeSquareMeters: 54,
    furnished: false,
    availableFrom: "2026-09-05",
    availableTo: "2027-09-04",
    minimumRentalMonths: 12,
    amenities: ["laundry"],
    imageUrls: img("gbg002", 3),
    contactCapability: "manual_handoff",
    providerMetadata: { manualUrl: "https://example.invalid/apply/GBG-002" },
    isActive: true,
  },
  {
    id: "mock-gbg-003",
    provider: "mock",
    providerListingId: "GBG-003",
    canonicalUrl: "https://example.invalid/listings/GBG-003",
    title: "Room near Lindholmen",
    description: "Small room in a shared flat, five minutes from Campus Lindholmen.",
    address: "Lindholmsallén 10, Göteborg",
    city: "Gothenburg",
    area: "Lindholmen",
    latitude: 57.7060,
    longitude: 11.9390,
    monthlyRent: 6200,
    currency: "SEK",
    rooms: 1,
    sizeSquareMeters: 20,
    furnished: true,
    availableFrom: "2026-08-21",
    availableTo: "2027-06-30",
    minimumRentalMonths: 6,
    amenities: ["wifi", "laundry"],
    imageUrls: img("gbg003", 3),
    contactCapability: "provider_api",
    providerMetadata: {},
    isActive: true,
  },
];
